module.exports={
    INVALID_CONTENT_TYPE:"only application/x-www-form-urlencoded content-type bodies are supported on POST /token",
    INVALID_GRANT_TYPE:'unsupported grant_type requested',
    AUTHORIZATION_FAILED:'client authentication failed',
    TOKEN_EXPIRED:"Token expired or invalid",
    UNREGISTERED_CLIENT:"unregistered client.",
    INVALID_TENANT:"invalid tenant.",
    TENANT_MISSING:"missing tenant header",
    INVALID_PDF_STRUCTURE:'Invalid PDF structure.',
    TOKEN_UNAVAILABLE:"Token unavailable",
    INVALID_ENDPOINT:"Invalid API endpoint",
    MISSING_GRANT_PARAMETER:"missing required parameter(s) (grant_type)",
    INVALID_CLIENT:"no client authentication mechanism provided",
    UNKNOWN_JOB_TYPE:"Unknown Job Type, could not create job.",
    CREATED_BY_REQUIRED:"Invalid params: created_by is a required property for job creation",
    CONTENT_TYPE_INVALID:"Invalid content-type: Content-type header is invalid.",
    INVALID_FILE_FORMAT:"Invalid File: The file specified is not a valid format for this endpoint.",
    JOB_ID_REQUIRED:"Invalid params: job_id is a required property to upload files to a job",
    JOB_ID_REQUIRED_START_DOC:"Invalid params:job_id is a required property to Start document analysis",
    JOB_ID_REQUIRED_ENGINE_RESULT:"Invalid params: job_id is a required property for getting Engine result",
    FILE_ID_REQUIRED_ENGINE_RESULT:"Invalid params: file_id is a required property for getting Engine result",
    INVALID_FILE_ID:"Requested File_Id Doesn't Exist",
    JOB_ID_DOESNOT_EXISTS:"Requested Job_Id doesn'nt Exist",
    FILE_ID_DOESNOT_EXISTS:"Requested File_Id Doesn't Exist",
    FILE_ID_REQUIRED:"Invalid params: file_id is a required property for getting file",
    JOB_ID_REQUIRED_GET_DOCUMENT:"Invalid params: job_id is a required property for getting file",
    FILE_NOT_FOUND:"FILE_NOT_FOUND"
}